### ISSUE TITLE
Make it possible to have PDA closer

### ISSUE THREAD

**Issue by CuteWaterBeary** [IWhoI/SubnauticaVREnhancements#4]
The PDA is too far even at the closest setting with this mod making it impossible for me to see the text. This mod made the game playable for me until I realized the PDA was too far and my headset resolution too small to display the text clearly. Plz update this mod if u can.

**Comment by IWhoI** [comment]
I just tested it and that might be a bug since the distance slider isn't changing the distance anymore. I will look into it and get back to you when it's fixed. For now you can just move your head closer to the PDA.

**Comment by IWhoI** [comment]
Fixed in version 2.1.2

**Comment by CuteWaterBeary** [comment]
Thank you so much! You have made this game truly enjoyable.
