### ISSUE TITLE
Rift S controller 

### ISSUE THREAD

**Issue by gamersalpha** [IWhoI/SubnauticaVREnhancements#5]
Hello there

how to configure control rift S ?

playing with game pad ou keyboard is not immersif 

thanks

**Comment by IWhoI** [comment]
Subnautica and this mod does not support motion controllers.

**Comment by gamersalpha** [comment]
ok i talk in Subnautica discord and then ignore me, 

i think vr for subnautica is not priority


thanks for u works 

i stop play in VR

thanks
