### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by Okabintaro** [IWhoI/SubnauticaVREnhancements#6]
Hello. Thank you so much for your work on this mod. I enjoyed playing with it a lot.
That said I also would like to use snippets of your mod or use it as a reference for future VR modding myself.
Would you mind adding a license to the repository? If you don't you basically don't allow anyone to use your code, see [this explanation](https://choosealicense.com/no-permission/).

I would suggest using the [MIT License](https://choosealicense.com/licenses/mit/#suggest-this-license) since it's simple and some other Mod Authors also use it(e.g. [MrPurple6411](https://github.com/MrPurple6411/MrPurple6411-Subnautica-Mods/blob/main/LICENSE))

Thanks!

**Comment by IWhoI** [comment]
Done
