### ISSUE TITLE
RFE: tooltip size not changing with head movement

### ISSUE THREAD

**Issue by farmboy0** [IWhoI/SubnauticaVREnhancements#8]
Currently when you move your head closer to the PDA window the tool-tips there will shrink or get larger when you move farther away. This makes the tool-tips unreadable to me. Could you please add an option that this doesn't happen?

Similar thing happens with the options menu it will tilt more when you get closer making the options in the upper part of the window hard to read.

Basically please don't move the UI when the head is moved.

**Comment by IWhoI** [comment]
I will try to fix these in the next version.
