### ISSUE TITLE
Feature:  Fixed-position HUD

### ISSUE THREAD

**Issue by jrmoserbaltimore** [IWhoI/SubnauticaVREnhancements#9]
The HUD moves when the player's head turns.  It would be more comfortable (for me at least) if the HUD was dependent on the physical orientation, such that rotating with the right stick moved the HUD, but turning the player's head didn't.  This is largely because it's uncomfortable to shift my eyes to look way to my peripheral vision, even with the HUD moved back; I'd rather the thing I'm looking at be close to the center of my vision, and rather turn my head some than my eyes alone to do that.

Nice mod overall though!

**Comment by IWhoI** [comment]
Seems like a great idea. I will check how difficult it would be to do when I get back to Subnautica but you might move on to other games by the time I get to it ;)
